# rio configuration
#
# Reference: https://rioterm.com/docs/config
#
# resync via patched rio --write-config mode

# use-fork = true
# line-height = 1.0
theme = "kanagawabones"
# env-vars = []
# option-as-alt = "none"
# ignore-selection-foreground-color = false
confirm-before-quit = false
# grapheme-clustering = true
copy-on-select = true
# hide-mouse-cursor-when-typing = false
# draw-bold-text-with-light-colors = false
# enable-scroll-bar = true
# scrollback-history-limit = 10000
#
# [cursor]
# shape = "Block"
# blinking = false
# blinking-interval = 800

[navigation]
mode = "Plain"
# current-working-directory = true
# use-terminal-title = false
# hide-if-single = false
use-split = false
# open-config-with-split = true
# unfocused-split-opacity = 0.7
# max-tab-width = 240.0
#
# [window]
# width = 800
# height = 490
# mode = "Windowed"
# opacity = 1.0
# opacity-cells = false
# blur = false
# decorations = "Enabled"
# macos-use-unified-titlebar = false
# macos-use-shadow = true
# colorspace = "Srgb"
# quake-width-percentage = 1.0
# quake-height-percentage = 0.4
#
# [shell]
# args = ["--login"]
#
# [platform]
#
# [keyboard]
# disable-ctlseqs-alt = false
# ime-cursor-positioning = true
# forward-to-ime-modifier-mask = [
#     "shift",
#     "ctrl",
#     "alt",
#     "super",
# ]
#
# [title]
# placeholder = "▲"
# content = "\{{ TITLE || RELATIVE_PATH }}"
#
# [scroll]
# multiplier = 3.0
# divider = 1.0

[fonts]
family = "DejaVuSansM Nerd Font Mono"
features = ["ss02", "ss03", "ss05", "ss19"]
size = {{rio_font_size}}
# hinting = true
# use-drawable-chars = true
# disable-warnings-not-found = false
#
# [fonts.regular]
# family = "cascadiacode"
# style = "default"
#
# [fonts.bold]
# family = "cascadiacode"
# style = "default"
#
# [fonts.bold-italic]
# family = "cascadiacode"
# style = "default"
#
# [fonts.italic]
# family = "cascadiacode"
# style = "default"
#
# [editor]
# program = "vi"
# args = []
#
# [margin]
# top = 2.0
# right = 2.0
# bottom = 2.0
# left = 2.0
#
# [panel]
# row-gap = 0.0
# column-gap = 0.0
# border-width = 2.0
# border-radius = 0.0
#
# [panel.margin]
# top = 2.0
# right = 2.0
# bottom = 2.0
# left = 2.0
#
# [panel.padding]
# top = 5.0
# right = 5.0
# bottom = 5.0
# left = 5.0
#
# [developer]
# enable-fps-counter = false
# log-level = "OFF"
# enable-log-file = false
#
# [bindings]
# keys = []

# [renderer]
# disable-unfocused-render = false
# disable-occluded-render = false
# strategy = "Events"
# use-cpu = false
#
# [hints]
# alphabet = "jfkdls;ahgurieowpq"
#
# [[hints.rules]]
# regex = '(?:https?://|mailto:|ftp://|file:|ssh:|git://|ssh://|tel:|magnet:|ipfs://|ipns://|gemini://|gopher://|news:)(?:(?:\[[:0-9a-fA-F]+(?:[:0-9a-fA-F]*)+\](?::[0-9]+)?)|[\w\-.~:/?#@!$&*+,;=%]+(?:[\(\[]\w*[\)\]])?)+(?<![,.])|(?:\.\./|\./|(?<!\w)~/|(?:[\w][\w\-.]*/)*(?<!\w)\$[A-Za-z_]\w*/|\.[\w][\w\-.]*/|(?<![\w~/])/(?!/))(?:(?=[\w\-.~:/?#@!$&*+;=%]*\.)[\w\-.~:/?#@!$&*+;=%]+(?:(?<!:) (?!\w+://)(?!\.{0,2}/)(?!~/)[\w\-.~:/?#@!$&*+;=%]*[/.])*(?<!:)(?: +(?= *$))?|(?![\w\-.~:/?#@!$&*+;=%]*\.)[\w\-.~:/?#@!$&*+;=%]+(?:(?<!:) (?!\w+://)(?!\.{0,2}/)(?!~/)[\w\-.~:/?#@!$&*+;=%]+)*(?<!:)(?: +(?= *$))?)|(?=[\w\-.~:/?#@!$&*+;=%]*\.)(?<!\$\d*)(?<!\w)[\w][\w\-.]*/[\w\-.~:/?#@!$&*+;=%]+(?<!:)(?: +(?= *$))?'
# hyperlinks = true
# post-processing = true
# persist = false
#
# [hints.rules.action]
# action = "Open"
#
# [hints.rules.mouse]
# enabled = true
# mods = ["Alt"]
#
# [hints.rules.binding]
# key = "O"
# mods = [
#     "Control",
#     "Shift",
# ]
# mode = []
#
# [bell]
# audio = false
#
# [effects]
# custom-mouse-cursor = false
# trail-cursor = false
# trail-cursor-opacity = 1.0
# trail-cursor-decay = [
#     100,
#     400,
# ]
# trail-cursor-start-threshold = 2
