#!/bin/bash
#
# This script reorders and sorts git submodule repositories based on their actual paths (after potential previous moves).
# This operation doesn't trigger any effect on repo except updating .gitmodules file, which content is then deterministic and doesn't depend on history.
# That allows allows easy comparison between repos.

set -o errexit
set -o nounset
set -o pipefail

[ -f .gitmodules ] || (echo "not at repo root" ; false)
GMN=$(pwd)/.gitmodules.new
cp .gitmodules $GMN

# new layout
git submodule absorbgitdirs

# main loop
git submodule --quiet foreach '
    if [ "$name" != "$sm_path" ]
    then
        # move submodule repo
        mkdir -p $(dirname $toplevel/.git/modules/$sm_path)
        mv $toplevel/.git/modules/$name $toplevel/.git/modules/$sm_path
        # update repo config
        sed -i "s@^.\*worktree = .\*\$@&$(realpath --relative-to=$toplevel/.git/modules/$sm_path $toplevel/$sm_path)@" $toplevel/.git/modules/$sm_path/config
        # update worktree pointer
        sed -i "s@$name@$sm_path@" .git
        # update submodule name in main repo
        sed -i "s@^\[submodule \"$name\"\]\$@[submodule \"$sm_path\"]@" $GMN
        echo $name → $sm_path
    fi
' || (rm -f $GMN ; false)

# cleaning
find .git/modules -type d -empty -delete

# ordering + replace current list
cat $GMN |
    tr -s \\n @ |
    sed 's/@\[submodule/\n[submodule/g' |
    sort |
    tr -s @ \\n > .gitmodules
rm $GMN

# need fresh bootstrap
git submodule update --init &> /dev/null

echo "Commit .gitmodules now!"
