# shochu setup

packages = [
    "base",
    "noscreenlock",
]

[variables]
awesome_network_interface = "eth1"
awesome_disk_interface = "dm-2" # sdb2 (or use PV label)
awesome_xset_burn_period = "13000"
redshift_night_temperature = "5000K" # no big shift to red for pastis
alacritty_font_size = 18

# vim: filetype=cfg
