# sake setup

packages = [
    "base",
    "build_gcc",
    "build_gdb",
    "build_llvm",
]

[variables]
awesome_network_interface = "enp5s0"
awesome_disk_interface = "sda"
gtk_font_size = "12"
awesome_height = "30"
alacritty_font_size = 14

# vim: filetype=cfg
