# sake setup

packages = [
    "alacritty",
    "awesome",
    "bash",
    "bluetooth",
    "compose",
    "fonts",
    "gdb",
    "gtk",
    "redshift",
    "xkb",
    ]

[variables]
awesome_network_interface = "enp2s0"

# vim: filetype=cfg
