# sake setup

packages = [
    "alacritty",
    "awesome",
    "bash",
    "bluetooth",
    "compose",
    "fish",
    "fonts",
    "gdb",
    "git",
    "gtk",
    "redshift",
    "starship",
    "tmux",
    "vim",
    "xkb",
    ]

[variables]
awesome_network_interface = "enp2s0"
awesome_disk_interface = "sda"

# vim: filetype=cfg
