# shochu setup

packages = [
    "base",
    "laptop",
    "thinkpad",
]

[variables]
awesome_network_interface = "wlp3s0" # "enp5s0"
awesome_disk_interface = "nvme0n1"
alacritty_font_size = 10

# vim: filetype=cfg
