# suze setup

packages = [
    "alacritty",
    "awesome",
    "bash",
    "bluetooth",
    "compose",
    "fonts",
    "gdb",
    "git",
    "gtk",
    "laptop",
    "mac",
    "redshift",
    "starship",
    "xkb",
    ]

[variables]
awesome_network_interface = "ens5"
awesome_disk_interface = "sda"

# vim: filetype=cfg
