# suze setup

packages = [
    "alacritty",
    "awesome",
    "bash",
    "bluetooth",
    "gdb",
    "gtk",
    "laptop",
    "mac",
    "redshift",
    "xkb",
    ]

[variables]
awesome_network_interface = "ens5"
