# XXX to get info/timings:
# $ starship explain

# no newline
add_newline = false
# Always time before anything
format = "$time$all$directory$cmd_duration$jobs$status$character"

# do not waste a line, so half of the screen!
[line_break]
disabled = true

# no username
[username]
disabled = true

# correct hostname
[hostname]
ssh_only = false
disabled = false
format = '[@](bold blue)[$hostname](bold green) '
# trim_at = '.'

# add time
[time]
disabled = false
format = '[\[$time\]](white) '
time_format = '%R'

# useless
[python]
disabled = true

# pollution
[lua]
disabled = true

# 20ms to get version that we don't care of
[rust]
disabled = true

# dont be lost
[directory]
truncation_length = 6

# too slow
[battery]
disabled = true

# correct return code
[status]
map_symbol = true
disabled = false

# no git status versus remote
[git_status]
ahead = ""
behind = ""

# bash/fish
[shell]
disabled = false
fish_indicator = ""
bash_indicator = ""

# vim: filetype=cfg
