# XXX to get info/timings:
# $ starship explain

# no newline
add_newline = false
# time before anything
format = "$time$all$directory$cmd_duration$jobs$status$character"

# do not waste a line, so half of the screen!
[line_break]
disabled = true

# no username
[username]
disabled = true

# correct hostname
[hostname]
ssh_only = false
disabled = false
format = '[@](bold blue)[$hostname](bold green) '
# trim_at = '.'
# aliases = {}

# add time
[time]
disabled = false
format = '[\[$time\]](white) '
time_format = '%R'

# useless
[python]
disabled = true

# 20ms to get version that we don't care of
[rust]
disabled = true

# dont be lost
[directory]
truncation_length = 999

# too slow
[battery]
disabled = true

# correct return code
[status]
format = '[$status]($style) ' # no symbol that skrew up terminals
disabled = false

# no git status versus remote
[git_status]
ahead = ""
behind = ""
style = "bold purple"
disabled = true

# bash/fish
[shell]
disabled = false
fish_indicator = ""
bash_indicator = "BASH "
format = "[$indicator]($style)" # ! no trailing space
style = 'red bold'

# no cmake
[cmake]
disabled = true

# useless and waste time
[c]
disabled = true
[php]
disabled = true
[java]
disabled = true
[lua]
disabled = true
[perl]
disabled = true
[scala]
disabled = true


[hg_branch]
disabled = true

[conda]
style = "cyan"
format = "env [$environment]($style) " # no weird symbol

[cpp]
disabled = false

# vim: filetype=cfg
