# launcher theme (theme.lua colors)

[main]
font=monospace:size=14
width=60
lines=20

[colors]
# RRGGBBAA
background=222222ff
text=aaaaaaff
match=e5cfb5ff
selection=535d6cff
selection-text=ffffffff
selection-match=e5cfb5ff
border=535d6cff

[border]
width=1
radius=10
